version: "3.7"

services:
  rusos_atelier:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./rusos_atelier
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - rusos_atelier

volumes:
  static:
